# Generated by Django 3.1 on 2021-02-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_record_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
