# Generated by Django 3.1 on 2021-02-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
